// <auto-generated />
namespace MovieRater.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class TVShow : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TVShow));
        
        string IMigrationMetadata.Id
        {
            get { return "202109050121295_TVShow"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
